CREATE TABLE LIST_OF_USERS (
    id SERIAL UNIQUE PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(12),
    password VARCHAR(255)
);